### ISSUE TITLE
Fatal Error on re-installation

### ISSUE THREAD

**Issue by gah242s** [CiviCooP/org.civicoop.civiruleslogger#1]
With CiviCRM 4.7.6, civiruleslogger hits a fatal error when reinstalling after uninstall.  The database table is left in place, as one would expect.  However, when the installer sees that the table exists on subsequent installations, it errors out with a fatal error.  Simple workaround is to delete the table from the database.

**Comment by mattwire** [comment]
This issue is from 2016 ... probably not a problem any more
